# https://docs.drone.io/pipeline/docker/examples/languages/python/#python-example

kind: pipeline
type: docker
name: torch-GPU

steps:

- name: install
  image: nvcr.io/nvidia/pytorch:20.02-py3
  commands:
    - python --version
    - pip install pip -U
    - pip --version
    - nvidia-smi
    #- pip install torch==1.3
    - pip install -r requirements.txt --user
    - pip install coverage pytest pytest-cov pytest-flake8 codecov
    - pip install -r ./tests/requirements.txt --user
    - pip list

- name: testing
  image: nvcr.io/nvidia/pytorch:20.02-py3
  commands:
    - export SLURM_LOCALID=0
    - python -c "import torch ; print(' & '.join([torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())]) if torch.cuda.is_available() else 'only CPU')"
    - coverage run --source pytorch_lightning -m py.test pytorch_lightning tests pl_examples -v --doctest-modules #  --flake8
    - coverage report
    - codecov --token d0fcb731-42af-465d-b680-c1ccdc824bdc --pr ${DRONE_PULL_REQUEST} --build ${DRONE_BUILD_NUMBER} --branch ${DRONE_BRANCH} --commit ${DRONE_COMMIT} --tag ${DRONE_TAG}

#- name: codecov
#  image: plugins/codecov
#  settings:
#    token: d0fcb731-42af-465d-b680-c1ccdc824bdc
#    files:
#      - *.xml
